[package]
name = "link"
version = "0.1.1"
authors = ["CrLF0710 <crlf0710@gmail.com>"]
description = "Now deprecated."
license = "MIT"
repository = "https://github.com/crlf0710/link-rs"

[dependencies]
